// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// brLoop
NumericMatrix brLoop(NumericVector x);
RcppExport SEXP rface_brLoop(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(brLoop(x));
    return __result;
END_RCPP
}
// getNorm
NumericVector getNorm(NumericMatrix x);
RcppExport SEXP rface_getNorm(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    __result = Rcpp::wrap(getNorm(x));
    return __result;
END_RCPP
}
// mat_of_faces
arma::Mat<double> mat_of_faces(List x, int nrow, int ncol);
RcppExport SEXP rface_mat_of_faces(SEXP xSEXP, SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    __result = Rcpp::wrap(mat_of_faces(x, nrow, ncol));
    return __result;
END_RCPP
}
// mat_to_image
arma::Cube<double> mat_to_image(NumericMatrix x, NumericVector dim);
RcppExport SEXP rface_mat_to_image(SEXP xSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dim(dimSEXP);
    __result = Rcpp::wrap(mat_to_image(x, dim));
    return __result;
END_RCPP
}
// rbrLoop
NumericMatrix rbrLoop(NumericVector x);
RcppExport SEXP rface_rbrLoop(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(rbrLoop(x));
    return __result;
END_RCPP
}
